title: Cfaz.net
baseurl: ""
baseurl_root: "site.cfaz.net"
url: "https://site.cfaz.net"
twitter_username: jekyllrb
github_username:  jekyll
include: 
  - CNAME

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

languages: ["pt-BR", "en", "es"]