title: Cfaz.net
baseurl: ""
baseurl_root: "cfaz.net"
url: "https://cfaz.net"
twitter_username: jekyllrb
github_username:  jekyll
include: 
  - CNAME

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

languages: ["pt-br", "en", "es"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: pt-br
languageNames:
  pt-br: Portugues
  en: Inglês
  es: Espanhol

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]