title: Cfaz.net
baseurl: "/"
url: "https://site.cfaz.net"
twitter_username: jekyllrb
github_username:  jekyll

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

languages: ["pt-BR", "en", "es"]