name: Integrity Tests
on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

jobs:
  Tests:
    runs-on: ubuntu-latest

    services:
      browser:
        image: selenium/standalone-chrome-debug
        ports:
          - "5900:5900" #for VNC access
          - "4444:4444" #for webdriver access

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
          bundler-cache: true