name: Kamal Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Kamal command to run"
        default: "kamal app details"
        required: true
      message_deploy:
        description: 'Message deploy'
        required: false

jobs:
  Command:
    runs-on: ubuntu-latest

    env:
      RAILS_MASTER_KEY: ${{ secrets.MASTER_KEY }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true

      - name: Install dependencies kamal
        run: gem install kamal -v 1.8.0

      - name: Set up Docker Buildx for cache
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Expose GitHub Runtime for cache
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Run Kamal command
        run: ${{ github.event.inputs.command }}

      - name: Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Deploy Cfaz
          DISCORD_AVATAR: https://yt3.googleusercontent.com/9TfKXVz92_hZby_4kscMRl7oGpem8j7DlvQXd0nZ251mddVy1yHcMBfiej2Lk4M9rpTJOAxrxeE=s176-c-k-c0x00ffffff-no-rj
          DISCORD_EMBEDS: '[    {
          "author": {  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "name": "${{ github.actor }}", "url": "https://github.com/${{github.actor}}" },
          "url": "https://github.com/${{github.repository}}/commit/${{github.sha}}",
          "fields": [
          { "name": "Deploy Cfaz Site", "value": "`${{github.event.inputs.message_deploy}}`" },
          { "name": "Job", "value": "${{github.job}}", "inline": true },
          { "name": "Event", "value": "${{github.event_name}}", "inline": true }
          ],
          "color":65280,
          "timestamp": "${{github.event.head_commit.timestamp}}",
          "footer":{"text": "${{github.event.head_commit.timestamp}}"}
          }    ]'
